### ISSUE TITLE
USBTO3DO-FZ1 can't load boot.iso

### ISSUE THREAD

**Issue by rapiqui** [tzmwx/USBTO3DO-FZ1#2]
Hi,

I made a USBTO3DO-FZ1, uploaded .uf2 compiled from François Caron github src and boot.iso from fixelsan and I am unable to boot the ODE.
The FZ-1 starts up, shows the 3DO logo for a brief second and screen remains black for 30 swc approximately. Then, the 3DO logo is shown again briefly but this time the ACCESS led turns on (as it does the ODE led) until next 3DO logo presentation for a second with no drive access in an endless loop.

I've tried two FZ-1 units, both functional with the original disc drive, and behaves the same way.
I used a raspberry pi pico RP2040 264Kb RAM and 4Mb Flash, which has TP2 and TP3 pads. Crossed them on the USB port as per the instructions.
Tested two different USB FAT32 drives.

Any hint will be welcome. Thanks

**Comment by tzmwx** [comment]
give me your email

| |
tzmwx20190126
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/18/2023 16:49 |
| To | tzmwx/USBTO3DO-FZ1 ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [tzmwx/USBTO3DO-FZ1] USBTO3DO-FZ1 can't load boot.iso (Issue #2) |

Hi,

I made a USBTO3DO-FZ1, uploaded .uf2 compiled from François Caron github src and boot.iso from fixelsan and I am unable to boot the ODE.
The FZ-1 starts up, shows the 3DO logo for a brief second and screen remains black for 30 swc approximately. Then, the 3DO logo is shown again briefly but this time the ACCESS led turns on (as it does the ODE led) until next 3DO logo presentation for a second with no drive access in an endless loop.

I've tried two FZ-1 units, both functional with the original disc drive, and behaves the same way.
I used a raspberry pi pico RP2040 264Kb RAM and 4Mb Flash, which has TP2 and TP3 pads. Crossed them on the USB port as per the instructions.
Tested two different USB FAT32 drives.

Any hint will be welcome. Thanks

**Comment by rapiqui** [comment]
Sorry, I think I can't paste any email address as it will be masked by github. In fact I could not see yours. I understand that the problem might be the firmware then?

**Comment by rapiqui** [comment]
Closing issue after having support from his creator. Thank you!
