### ISSUE TITLE
UF2 File needed

### ISSUE THREAD

**Issue by veb-xenon** [tzmwx/USBTO3DO-FZ1#3]
Hello, I would need to have the UF2 file because my PiPico went incidentally erased, so I'm unable to boot anymore my USBTO3DO on my FZ1. Thank you!

Now I only get a "Insert Disc" and the 3DO bios presentation, and if I try the UF2 from FCare I get a black screen and green light in my console...

**Comment by tzmwx** [comment]
因为这个开源项目只支持自己制作，不支持买卖，不能用于商业用途！你们的卖家违反了约定，所以不会提供固件！
![IMG_3357](https://github.com/tzmwx/USBTO3DO-FZ1/assets/129564095/a7f13c1e-6dc6-46dc-91af-099ebff6b261)

**Comment by veb-xenon** [comment]
Ok, no problem. I was polite, and I'm a person with no soldier and electronics skills, so I've bought a premade one, not all people can be do it. Not a thief, the ODE is only for me. I've tried to compile the UF2 and I've been unable to run it. Sorry. And good luck.
