### ISSUE TITLE
Firmware file

### ISSUE THREAD

**Issue by soviet9922** [tzmwx/USBTO3DO-FZ1#4]
Hi, purchased one of this devices but can't find the .uf2 firmware file anywhere is like a secret well kept.
Maybe you could share the file please please please :).
Could love to get my 3do working again.

**Comment by tzmwx** [comment]
这个项目不支持商业销售，请联系你的卖家进行退货
![IMG_4193](https://github.com/tzmwx/USBTO3DO-FZ1/assets/129564095/33d4350b-3fe6-41c7-83f1-19ec60a721fb)
